In [1]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print([x*y])

[tensor([10.,  3.])]


In [2]:
x = torch.zeros([2, 5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2, 5])

In [6]:
y

tensor([[0.7883, 0.9353, 0.9883, 0.8910, 0.6084],
        [0.1120, 0.3136, 0.2607, 0.2382, 0.1142]])

In [7]:
y.view([1, 10])

tensor([[0.7883, 0.9353, 0.9883, 0.8910, 0.6084, 0.1120, 0.3136, 0.2607, 0.2382,
         0.1142]])

In [8]:
y = y.view([1, 10])

In [9]:
y

tensor([[0.7883, 0.9353, 0.9883, 0.8910, 0.6084, 0.1120, 0.3136, 0.2607, 0.2382,
         0.1142]])

In [10]:
y.shape

torch.Size([1, 10])